
const data = [
	{
		id: 1,
		empresa: "Photosnap",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720850/Jobs%20listing/photosnap_veodak.svg",
		nuevo: true,
		destacado: true,
		posicion: "Senior Frontend Developer",
		rol: "Frontend",
		nivel: "Senior",
		publicado: "1d ago",
		contrato: "Full Time",
		localidad: "USA Only",
		lenguajes: ["HTML", "CSS", "JavaScript"],
		herramientas: []
	},
	{
		id: 2,
		empresa: "Manage",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720825/Jobs%20listing/manage_uzt256.svg",
		nuevo: true,
		destacado: true,
		posicion: "Fullstack Developer",
		rol: "Fullstack",
		nivel: "Midweight",
		publicado: "1d ago",
		contrato: "Part Time",
		localidad: "Remote",
		lenguajes: ["Python"],
		herramientas: ["React"]
	},
	{
		id: 3,
		empresa: "Account",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647662045/Jobs%20listing/account_klrbiu.svg",
		nuevo: true,
		destacado: false,
		posicion: "Junior Frontend Developer",
		rol: "Frontend",
		nivel: "Junior",
		publicado: "2d ago",
		contrato: "Part Time",
		localidad: "USA Only",
		lenguajes: ["JavaScript"],
		herramientas: ["React", "Sass"]
	},
	{
		id: 4,
		empresa: "MyHome",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720841/Jobs%20listing/myhome_mq4pfb.svg",
		nuevo: false,
		destacado: false,
		posicion: "Junior Frontend Developer",
		rol: "Frontend",
		nivel: "Junior",
		publicado: "5d ago",
		contrato: "contrato",
		localidad: "USA Only",
		lenguajes: ["CSS", "JavaScript"],
		herramientas: []
	},
	{
		id: 5,
		empresa: "Loop Studios",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720816/Jobs%20listing/loop-studios_doiuvf.svg",
		nuevo: false,
		destacado: false,
		posicion: "Software Engineer",
		rol: "FullStack",
		nivel: "Midweight",
		publicado: "1w ago",
		contrato: "Full Time",
		localidad: "Worldwide",
		lenguajes: ["JavaScript"],
		herramientas: ["Ruby", "Sass"]
	},
	{
		id: 6,
		empresa: "FaceIt",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720710/Jobs%20listing/faceit_h38lng.svg",
		nuevo: false,
		destacado: false,
		posicion: "Junior Backend Developer",
		rol: "Backend",
		nivel: "Junior",
		publicado: "2w ago",
		contrato: "Full Time",
		localidad: "UK Only",
		lenguajes: ["Ruby"],
		herramientas: ["RoR"]
	},
	{
		id: 7,
		empresa: "Shortly",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720859/Jobs%20listing/shortly_hfgafv.svg",
		nuevo: false,
		destacado: false,
		posicion: "Junior Developer",
		rol: "Frontend",
		nivel: "Junior",
		publicado: "2w ago",
		contrato: "Full Time",
		localidad: "Worldwide",
		lenguajes: ["HTML", "JavaScript"],
		herramientas: ["Sass"]
	},
	{
		id: 8,
		empresa: "Insure",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720741/Jobs%20listing/insure_dypwit.svg",
		nuevo: false,
		destacado: false,
		posicion: "Junior Frontend Developer",
		rol: "Frontend",
		nivel: "Junior",
		publicado: "2w ago",
		contrato: "Full Time",
		localidad: "USA Only",
		lenguajes: ["JavaScript"],
		herramientas: ["Vue", "Sass"]
	},
	{
		id: 9,
		empresa: "Eyecam Co.",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720701/Jobs%20listing/eyecam-co_wpqdwp.svg",
		nuevo: false,
		destacado: false,
		posicion: "Full Stack Engineer",
		rol: "Fullstack",
		nivel: "Midweight",
		publicado: "3w ago",
		contrato: "Full Time",
		localidad: "Worldwide",
		lenguajes: ["JavaScript", "Python"],
		herramientas: ["Django"]
	},
	{
		id: 10,
		empresa: "The Air Filter Company",
		logo: "https://res.cloudinary.com/academia-geek-1/image/upload/v1647720869/Jobs%20listing/the-air-filter-company_pjwk70.svg",
		nuevo: false,
		destacado: false,
		posicion: "Front-end Dev",
		rol: "Frontend",
		nivel: "Junior",
		publicado: "1mo ago",
		contrato: "Part Time",
		localidad: "Worldwide",
		lenguajes: ["JavaScript"],
		herramientas: ["React", "Sass"]
	}
];

export default data;
